// ─── StyleProfile — Type Definitions ─────────────────────────────────────────
// Single source of truth for all data shapes in the style profile system.

// ── Raw correction captured when user edits AI output ────────────────────────

export interface Correction {
  id: string
  timestamp: number
  /** Original AI-generated text (single row) */
  before: string
  /** User's corrected version */
  after: string
  /** Similarity score 0–1 (1 = no change) */
  similarity: number
  /** Detected change categories */
  tags: CorrectionTag[]
  /** Which chapter/file this came from */
  sourceFile?: string
}

export type CorrectionTag =
  | 'shorten' // ย่อให้สั้นลง
  | 'expand' // ขยายความ
  | 'formality-up' // เป็นทางการขึ้น
  | 'formality-down' // ลดความเป็นทางการ
  | 'word-swap' // เปลี่ยนคำเฉพาะ
  | 'restructure' // เรียงประโยคใหม่
  | 'punctuation' // แก้วรรคตอน
  | 'nuance' // ปรับความหมายละเอียด
  | 'remove-filler' // ตัดคำฟุ่มเฟือย
  | 'naturalness' // ทำให้เป็นธรรมชาติขึ้น

// ── Analyzed style pattern (derived from many corrections) ────────────────────

export interface StylePattern {
  tag: CorrectionTag
  /** How often this tag appears, 0–1 */
  frequency: number
  /** Example before/after pairs illustrating this pattern */
  examples: Array<{ before: string; after: string }>
}

// ── The full style profile for a project ─────────────────────────────────────

export interface StyleProfile {
  id: string
  projectName: string
  createdAt: number
  updatedAt: number
  /** Raw correction log */
  corrections: Correction[]
  /** Analyzed patterns (updated by AI analyzer) */
  patterns: StylePattern[]
  /** Human-readable style guide generated by AI */
  styleGuide: string
  /** Short summary injected into AI system prompt */
  promptSnippet: string
  /** Whether analysis is stale (new corrections since last analyze) */
  isDirty: boolean
  /** Stats */
  stats: ProfileStats
}

export interface ProfileStats {
  totalCorrections: number
  avgSimilarity: number
  mostCommonTags: CorrectionTag[]
  correctionsByDay: Record<string, number> // ISO date → count
}

// ── Store interface exposed to React components ───────────────────────────────

export interface StyleProfileStore {
  profile: StyleProfile | null
  isAnalyzing: boolean
  analyzeError: string | null

  // Actions
  addCorrection: (before: string, after: string, sourceFile?: string) => void
  analyze: (apiKey: string) => Promise<void>
  clearCorrections: () => void
  resetProfile: () => void
  loadProfile: (raw: StyleProfile) => void
  getPromptSnippet: () => string
}

// ── Diff result between two strings ──────────────────────────────────────────

export interface DiffResult {
  similarity: number
  tags: CorrectionTag[]
  lengthDelta: number // chars: negative = shorter, positive = longer
  wordDelta: number // words
  changedWordPairs: Array<{ from: string; to: string }>
}
